else_if_brace_style="ClosingNextLine"

max_width = 100
ideal_width = 80
tab_spaces = 4
fn_call_width = 80
struct_lit_width = 16
newline_style = "Unix"
fn_brace_style = "PreferSameLine"
fn_return_indent = "WithArgs"
fn_args_paren_newline = true
fn_args_density = "Compressed"
fn_args_layout = "Visual"
fn_arg_indent = "Visual"
where_density = "Compressed"
where_indent = "Visual"
where_layout = "Horizontal"
where_pred_indent = "Visual"
generics_indent = "Visual"
struct_trailing_comma = "Vertical"
struct_lit_trailing_comma = "Vertical"
struct_lit_style = "Block"
struct_lit_multiline_style = "PreferSingle"
enum_trailing_comma = true
reorder_imports = true
format_strings = true
chains_overflow_last = true
take_source_hints = true
normalise_comments = false
wrap_comments = false
