# input file path
input_path = "/path/to/input/file"

# output file path
output_path = "/path/to/output/file"

# original genome length
original_genome_length = 100

# minimal weight of the edge in De Bruijn Graph
minimal_weight_threshold = 0

# input file type, currently can have one of threes values:
# BFCounter, Fasta, Fastq
input_file_type = "Fastq"
